// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PsychoCitas.Domain.Enums;
using PsychoCitas.Infrastructure.Persistence;

#nullable disable

namespace PsychoCitas.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330011853_PR10_Fase2_PaymentAutomation")]
    partial class PR10_Fase2_PaymentAutomation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_cita", new[] { "programada", "confirmada", "completada", "cancelada", "no_asistio", "reagendada" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "modalidad", new[] { "presencial", "videollamada", "telefonica" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_sesion", new[] { "individual", "pareja", "familia", "grupo", "evaluacion", "seguimiento" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PsychoCitas.Domain.Entities.Cita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime?>("CanceladoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelado_en");

                    b.Property<Guid?>("CanceladoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelado_por");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid?>("CreadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por");

                    b.Property<bool>("EsPrimeraVez")
                        .HasColumnType("boolean")
                        .HasColumnName("es_primera_vez");

                    b.Property<EstadoCita>("Estado")
                        .HasColumnType("estado_cita")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("LinkVideollamada")
                        .HasColumnType("text")
                        .HasColumnName("link_videollamada");

                    b.Property<Modalidad>("Modalidad")
                        .HasColumnType("modalidad")
                        .HasColumnName("modalidad");

                    b.Property<string>("MotivoCancelacion")
                        .HasColumnType("text")
                        .HasColumnName("motivo_cancelacion");

                    b.Property<string>("NotasPrevias")
                        .HasColumnType("text")
                        .HasColumnName("notas_previas");

                    b.Property<int?>("NumeroSesion")
                        .HasColumnType("integer")
                        .HasColumnName("numero_sesion");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<Guid>("PsicologoId")
                        .HasColumnType("uuid")
                        .HasColumnName("psicologo_id");

                    b.Property<Guid?>("RecurrenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("recurrencia_id");

                    b.Property<TipoSesion>("TipoSesion")
                        .HasColumnType("tipo_sesion")
                        .HasColumnName("tipo_sesion");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("citas", (string)null);
                });

            modelBuilder.Entity("PsychoCitas.Domain.Entities.DocumentoPaciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("UrlStorage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("documentos_paciente", (string)null);
                });

            modelBuilder.Entity("PsychoCitas.Domain.Entities.EventoPago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IntentoPagoId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Proveedor")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderEventId")
                        .HasColumnType("text");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IntentoPagoId");

                    b.ToTable("EventosPago");
                });

            modelBuilder.Entity("PsychoCitas.Domain.Entities.HistoriaClinica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Alergias")
                        .HasColumnType("text")
                        .HasColumnName("alergias");

                    b.Property<string>("AntecedentePersonales")
                        .HasColumnType("text")
                        .HasColumnName("antecedentes_personales");

                    b.Property<string>("AntecedentesFamiliares")
                        .HasColumnType("text")
                        .HasColumnName("antecedentes_familiares");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("DiagnosticoCie11")
                        .HasColumnType("text")
                        .HasColumnName("diagnostico_cie11");

                    b.Property<string>("DiagnosticoInicial")
                        .HasColumnType("text")
                        .HasColumnName("diagnostico_inicial");

                    b.Property<DateOnly?>("FechaAlta")
                        .HasColumnType("date")
                        .HasColumnName("fecha_alta");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso");

                    b.Property<string>("MedicacionActual")
                        .HasColumnType("text")
                        .HasColumnName("medicacion_actual");

                    b.Property<string>("MotivoConsulta")
                        .HasColumnType("text")
                        .HasColumnName("motivo_consulta");

                    b.Property<string>("ObjetivosTerapeuticos")
                        .HasColumnType("text")
                        .HasColumnName("objetivos_terapeuticos");

                    b.Property<string>("ObservacionesIniciales")
                        .HasColumnType("text")
                        .HasColumnName("observaciones_iniciales");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<Guid>("PsicologoId")
                        .HasColumnType("uuid")
                        .HasColumnName("psicologo_id");

                    b.Property<string>("TratamientosPrevios")
                        .HasColumnType("text")
                        .HasColumnName("tratamientos_previos");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId")
                        .IsUnique();

                    b.ToTable("historia_clinica", (string)null);
                });

            modelBuilder.Entity("PsychoCitas.Domain.Entities.IntentoPago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CheckoutUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiraEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("text");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PagoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Proveedor")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderPaymentId")
                        .HasColumnType("text");

                    b.Property<string>("RawResponse")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PagoId");

                    b.ToTable("IntentosPago");
                });

            modelBuilder.Entity("PsychoCitas.Domain.Entities.NotaSesion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccionesRiesgo")
                        .HasColumnType("text")
                        .HasColumnName("acciones_riesgo");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("AvanceObjetivos")
                        .HasColumnType("text")
                        .HasColumnName("avance_objetivos");

                    b.Property<Guid>("CitaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cita_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<int?>("EstadoAnimo")
                        .HasColumnType("integer")
                        .HasColumnName("estado_animo");

                    b.Property<bool>("EvaluacionRiesgo")
                        .HasColumnType("boolean")
                        .HasColumnName("evaluacion_riesgo");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("boolean")
                        .HasColumnName("finalizada");

                    b.Property<int?>("NivelAnsiedad")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_ansiedad");

                    b.Property<int?>("NivelRiesgo")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_riesgo");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("PlanProximaSesion")
                        .HasColumnType("text")
                        .HasColumnName("plan_proxima_sesion");

                    b.Property<Guid>("PsicologoId")
                        .HasColumnType("uuid")
                        .HasColumnName("psicologo_id");

                    b.Property<string>("ResumenSesion")
                        .HasColumnType("text")
                        .HasColumnName("resumen_sesion");

                    b.Property<string>("TareasAsignadas")
                        .HasColumnType("text")
                        .HasColumnName("tareas_asignadas");

                    b.Property<List<string>>("TecnicasUsadas")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tecnicas_usadas");

                    b.HasKey("Id");

                    b.HasIndex("CitaId")
                        .IsUnique();

                    b.ToTable("notas_sesion", (string)null);
                });

            modelBuilder.Entity("PsychoCitas.Domain.Entities.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("CitaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EnviadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorDetalle")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer");

                    b.Property<string>("Mensaje")
                        .HasColumnType("text");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ProgramadaPara")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("CitaId", "Canal", "Tipo")
                        .IsUnique();

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("PsychoCitas.Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("ContactoEmergencia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contacto_emergencia");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Dni")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado_civil");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Genero")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("genero");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("Ocupacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ocupacion");

                    b.Property<string>("ReferidoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("referido_por");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("TelefonoEmergencia")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono_emergencia");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique()
                        .HasFilter("dni IS NOT NULL");

                    b.HasIndex("Email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("Apellidos", "Nombres");

                    b.ToTable("pacientes", (string)null);
                });

            modelBuilder.Entity("PsychoCitas.Domain.Entities.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CitaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cita_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<string>("MetodoPago")
                        .HasColumnType("text")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric")
                        .HasColumnName("monto");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_pagado");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<string>("NumeroOperacion")
                        .HasColumnType("text")
                        .HasColumnName("numero_operacion");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<DateTime?>("PagadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pagado_en");

                    b.Property<Guid?>("RegistradoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("registrado_por");

                    b.HasKey("Id");

                    b.HasIndex("CitaId")
                        .IsUnique();

                    b.ToTable("pagos", (string)null);
                });

            modelBuilder.Entity("PsychoCitas.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("PsychoCitas.Domain.Entities.Cita", b =>
                {
                    b.HasOne("PsychoCitas.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("PsychoCitas.Domain.Entities.DocumentoPaciente", b =>
                {
                    b.HasOne("PsychoCitas.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Documentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("PsychoCitas.Domain.Entities.EventoPago", b =>
                {
                    b.HasOne("PsychoCitas.Domain.Entities.IntentoPago", "IntentoPago")
                        .WithMany()
                        .HasForeignKey("IntentoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntentoPago");
                });

            modelBuilder.Entity("PsychoCitas.Domain.Entities.HistoriaClinica", b =>
                {
                    b.HasOne("PsychoCitas.Domain.Entities.Paciente", "Paciente")
                        .WithOne("HistoriaClinica")
                        .HasForeignKey("PsychoCitas.Domain.Entities.HistoriaClinica", "PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("PsychoCitas.Domain.Entities.IntentoPago", b =>
                {
                    b.HasOne("PsychoCitas.Domain.Entities.Pago", "Pago")
                        .WithMany()
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("PsychoCitas.Domain.Entities.NotaSesion", b =>
                {
                    b.HasOne("PsychoCitas.Domain.Entities.Cita", "Cita")
                        .WithOne("Nota")
                        .HasForeignKey("PsychoCitas.Domain.Entities.NotaSesion", "CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("PsychoCitas.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("PsychoCitas.Domain.Entities.Cita", "Cita")
                        .WithMany("Notificaciones")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("PsychoCitas.Domain.Entities.Pago", b =>
                {
                    b.HasOne("PsychoCitas.Domain.Entities.Cita", "Cita")
                        .WithOne("Pago")
                        .HasForeignKey("PsychoCitas.Domain.Entities.Pago", "CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("PsychoCitas.Domain.Entities.Cita", b =>
                {
                    b.Navigation("Nota");

                    b.Navigation("Notificaciones");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("PsychoCitas.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Documentos");

                    b.Navigation("HistoriaClinica");
                });
#pragma warning restore 612, 618
        }
    }
}
